.TH autols 1  "USER COMMANDS"
.SH NAME
autols \- automatically generate output of ls command in a designated terminal following cd command from any other terminal
.SH SYNOPSIS
.B alias
cd= '. autocd'
.TP 
.B autols
[\-s] [\-d delay in ms]
.TP 
.B autols
[\-e]
.SH DESCRIPTION
Autols eliminates the need to execute the ls command after every directory change. It displays the path and contents of the current working directory of the terminal which most recently executed the cd command. Setup requires autols -s with optional -d to set refresh rate in the monitoring terminal. Usage requires using '. autocd' command in place of the 'cd' command or simply cd with the appropriate alias.
.SH OPTIONS
.TP
\-s
start autols in monitoring terminal
.TP
\-d
set refresh rate in milliseconds ( to be used with -s ) 500 by deafult
.TP
\-e
end autols monitoring from any terminal
.SH AUTHOR
Jacob Condello (jake.condello (at) gmail.com)
